version: '2.1'

services:
  postgres:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:13.2
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'


volumes:
  postgres:
