version: '2.1'

services:
  oxidauth:
    image: registry.vizerapp.dev/lib/oxidauth-api:2021.26.3
    stdin_open: true
    tty: true
    ports:
      - "8084:80"
    env_file:
      - .env
    links:
      - oxidauth-postgres
    depends_on:
      - oxidauth-setup
      - oxidauth-postgres

  oxidauth-setup:
    image: registry.vizerapp.dev/lib/oxidauth-api:2021.26.3
    command: /bin/bash -c "/bin/setup.sh"
    stdin_open: true
    tty: true
    env_file:
      - .env
    links:
      - oxidauth-postgres
    depends_on:
      - oxidauth-postgres

  oxidauth-postgres:
    command: ["postgres", "-c", "log_statement=all"]
    image: postgres:13.2
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - 'oxidauth-postgres-vol:/var/lib/postgresql/data' 
    healthcheck:
      test: ["/bin/sh", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  oxidauth-postgres-vol:
